### ISSUE TITLE
Make a new button to Export iCal to MS Outlook

### ISSUE THREAD

**Issue by i2000s** [afragen/the-events-calendar-outlook-import-fix#1]
Hi there,

I am working on making the iCal exporter compatible with both Apple and MS Outlook formats. My plan is to make a separate button dedicated to the MS Outlook format exporter. See WIP [here](http://cquic.unm.edu/event/pioneers-in-quantum-optics-and-quantum-information-science-celebration-of-the-academic-life-of-carlton-m-caves/). But I am not sure how to integrate your code which basically corrected the line ending if I understand it correctly, into a self-defined function under my theme folder. I guess maybe I can make a class similar to `Tribe__Events_iCal`, but not sure how to integrate your code in. As a php newbie, I appreciate if you can shadow a light on this implementation. 

Thanks,
Qi

**Comment by afragen** [comment]
Hey Qi,

What my code does is to remove the line beginning with `X-WR-CALNAME`. I found that this line cause an imported Outlook calendar event to create a new calendar not a new event. The code only removes this one line.

If your project is up on GitHub perhaps I might be able to see and help more.

I never really figured out how to only run this code when the user wanted. It runs all the time it's enabled. Your project seems like a good idea and feel free to use this code if it helps.

**Comment by i2000s** [comment]
Hi Andy,

Thank you for your kind word. My code can be found on [my gist](https://gist.github.com/i2000s/736159ea5dfaad6596503a0901f62846) as a part of my theme's `functions.php` file. So far, it does seem adding a button to the event page, but the exported iCal files are the same for both Outlook or Apple formats. I added an inherited class `CQuIC__Events__iCal` with your function inside to remove the one line and maybe also fix the line endings. I guess the class and functions I defined using your code might not be working. 

I also observe the line endings is not correct on Outlook (I don't have Mac/Apple to check the other iCal button). On [this page](http://stackoverflow.com/questions/666929/encoding-newlines-in-ical-files/12249023#12249023), it suggests to use `$description = str_replace("\r\n", "\\n", $description);` to escape the line endings in description. I am not sure where should I put this in my code.

I may have missed a lot of important essence of PHP coding as I am a newbie.
I appreciate if you can help make it work!
Qi
